export const Mascotines = [{
    id: 1,
    name: 'Baco',
    gender: 'Masculino',
    thumbnail:'../../assets/baco.jpg',
    owner: 'Cristian Pastorini',
    species:'Gato',
},
{
    id: 2,
    name: 'Kira',
    gender: 'Femenino',
    thumbnail:'../../assets/kira.jpg',
    owner: 'Rocco Nesci',
    species:'Perro',
},
{
    id: 3,
    name: 'Mora',
    gender: 'Femenino',
    thumbnail:'../../assets/mora.png',
    owner: 'Cristian Mouguelar',
    species:'Perro',
},
{
    id: 4,
    name: 'Nyun Nyun',
    gender: 'Masculino',
    thumbnail:'../../assets/nyun-nyun.jpg',
    owner: 'Darién Julián Ramirez Estevez',
    species:'Gato',
},
{
    id: 5,
    name: 'Joji',
    gender: 'Masculino',
    thumbnail:'../../assets/joji.jpg',
    owner: 'Brian Rodriguez',
    species:'Gato',
},
{
    id: 6,
    name: 'Eddy',
    gender: 'Masculino',
    thumbnail:'../../assets/eddy.jpeg',
    owner: 'Jorge Sosa',
    species:'Perro',
},
{
    id: 7,
    name: 'Raki',
    gender: 'Femenino',
    thumbnail:'../../assets/raki.jpg',
    owner: 'Roxana Armoa',
    species:'Gato',
},
{
    id: 8,
    name: 'Olivia',
    gender: 'Femenino',
    thumbnail:'../../assets/olivia.jpeg',
    owner: 'Mayelis Jimenez',
    species:'Perro',
},
{
    id: 9,
    name: 'Pitufa',
    gender: 'Femenino',
    thumbnail:'../../assets/pitufa.jpg',
    owner: 'German De Los Santos',
    species:'Perro',
},
{
    id: 10,
    name: 'Napoleon',
    gender: 'Masculino',
    thumbnail:'../../assets/napoleon.png',
    owner: 'Diego Bruno',
    species:'Perro',
},]; 